[project]
name = "tips"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faicons>=0.2.2",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "ridgeplot>=0.3.1",
    "shiny>=1.3.0",
    "shinywidgets>=0.5.1",
]
